/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'public-users': PublicUserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'public-users': PublicUser;
    abstracts: Abstract;
    latest_publications: LatestPublication;
    events: Event;
    media: Media;
    album_media: AlbumMedia;
    press_media: PressMedia;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'public-users': PublicUsersSelect<false> | PublicUsersSelect<true>;
    abstracts: AbstractsSelect<false> | AbstractsSelect<true>;
    latest_publications: LatestPublicationsSelect<false> | LatestPublicationsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    album_media: AlbumMediaSelect<false> | AlbumMediaSelect<true>;
    press_media: PressMediaSelect<false> | PressMediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'id') | ('en' | 'id')[];
  globals: {
    homepage_content: HomepageContent;
    about_content: AboutContent;
    events_content: EventsContent;
    publications_content: PublicationsContent;
    media_content: MediaContent;
    site_settings: SiteSetting;
  };
  globalsSelect: {
    homepage_content: HomepageContentSelect<false> | HomepageContentSelect<true>;
    about_content: AboutContentSelect<false> | AboutContentSelect<true>;
    events_content: EventsContentSelect<false> | EventsContentSelect<true>;
    publications_content: PublicationsContentSelect<false> | PublicationsContentSelect<true>;
    media_content: MediaContentSelect<false> | MediaContentSelect<true>;
    site_settings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'en' | 'id';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PublicUser;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PublicUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-users".
 */
export interface PublicUser {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'public-users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abstracts".
 */
export interface Abstract {
  id: number;
  event: number | Event;
  user?: (number | null) | PublicUser;
  main_author: string;
  affiliation: string;
  title: string;
  text: string;
  keywords: {
    keyword: string;
    id?: string | null;
  }[];
  citation: string;
  status: 'submitted' | 'under_review' | 'accepted' | 'rejected';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  start_date: string;
  end_date: string;
  title: string;
  location?: string | null;
  participants?: string | null;
  image?: (number | null) | Media;
  article?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  description?: string | null;
  show_on_homepage?: boolean | null;
  key_dates?:
    | {
        date: string;
        label: string;
        show?: boolean | null;
        id?: string | null;
      }[]
    | null;
  thematic_areas?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  sessions?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "latest_publications".
 */
export interface LatestPublication {
  id: number;
  title: string;
  description: string;
  source: string;
  date: string;
  tag: 'Policy brief' | 'Proceedings' | 'Publications' | 'Technical Outputs';
  file: number | Media;
  /**
   * Automatically detected from the uploaded file
   */
  file_type: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "album_media".
 */
export interface AlbumMedia {
  id: number;
  title: string;
  /**
   * This image will be used as the album thumbnail.
   */
  cover_image: number | Media;
  media_items?:
    | {
        type: 'photo' | 'video';
        /**
         * Upload a photo or video file.
         */
        file: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "press_media".
 */
export interface PressMedia {
  id: number;
  image: number | Media;
  source_logo: number | Media;
  source_name: string;
  title: string;
  date: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Select related press releases to display in the sidebar.
   */
  related_press?: (number | PressMedia)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'public-users';
        value: number | PublicUser;
      } | null)
    | ({
        relationTo: 'abstracts';
        value: number | Abstract;
      } | null)
    | ({
        relationTo: 'latest_publications';
        value: number | LatestPublication;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'album_media';
        value: number | AlbumMedia;
      } | null)
    | ({
        relationTo: 'press_media';
        value: number | PressMedia;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'public-users';
        value: number | PublicUser;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'public-users';
        value: number | PublicUser;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-users_select".
 */
export interface PublicUsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abstracts_select".
 */
export interface AbstractsSelect<T extends boolean = true> {
  event?: T;
  user?: T;
  main_author?: T;
  affiliation?: T;
  title?: T;
  text?: T;
  keywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  citation?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "latest_publications_select".
 */
export interface LatestPublicationsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  source?: T;
  date?: T;
  tag?: T;
  file?: T;
  file_type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  start_date?: T;
  end_date?: T;
  title?: T;
  location?: T;
  participants?: T;
  image?: T;
  article?: T;
  description?: T;
  show_on_homepage?: T;
  key_dates?:
    | T
    | {
        date?: T;
        label?: T;
        show?: T;
        id?: T;
      };
  thematic_areas?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  sessions?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "album_media_select".
 */
export interface AlbumMediaSelect<T extends boolean = true> {
  title?: T;
  cover_image?: T;
  media_items?:
    | T
    | {
        type?: T;
        file?: T;
        caption?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "press_media_select".
 */
export interface PressMediaSelect<T extends boolean = true> {
  image?: T;
  source_logo?: T;
  source_name?: T;
  title?: T;
  date?: T;
  content?: T;
  related_press?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_content".
 */
export interface HomepageContent {
  id: number;
  hero_section?: {
    /**
     * Select an event to display in the hero section
     */
    featured_event?: (number | null) | Event;
    /**
     * Upload a custom background image for the hero section.
     */
    background_image?: (number | null) | Media;
    title?: string | null;
    subtitle?: string | null;
    register_cta?: string | null;
    register_cta_url?: string | null;
    explore_cta?: string | null;
    explore_cta_url?: string | null;
  };
  about_section?: {
    label?: string | null;
    title?: string | null;
    description?: string | null;
    boxes?:
      | {
          icon: 'globe' | 'stakeholder' | 'book' | 'bulb';
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  upcoming_forum_section?: {
    featured_event?: (number | null) | Event;
    label?: string | null;
    register_cta?: string | null;
    register_cta_url?: string | null;
    view_program_cta?: string | null;
    view_program_cta_url?: string | null;
  };
  publications_section?: {
    label?: string | null;
    title?: string | null;
    view_all_text?: string | null;
    download_cta?: string | null;
  };
  contact_section?: {
    label?: string | null;
    title?: string | null;
    description?: string | null;
    contact_items?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    form_name_placeholder?: string | null;
    form_name_label?: string | null;
    form_email_placeholder?: string | null;
    form_email_label?: string | null;
    form_subject_placeholder?: string | null;
    form_subject_label?: string | null;
    form_message_placeholder?: string | null;
    form_message_label?: string | null;
    form_privacy_text?: string | null;
    form_submit_cta?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_content".
 */
export interface AboutContent {
  id: number;
  hero_section?: {
    label?: string | null;
    title?: string | null;
    description?: string | null;
    /**
     * Recommended size: 703x552px or similar aspect ratio. Image will be cropped to fill the container.
     */
    image?: (number | null) | Media;
  };
  mission_section?: {
    label?: string | null;
    title?: string | null;
    description?: string | null;
    read_more_text?: string | null;
    read_more_url?: string | null;
    objectives?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  milestones_section?: {
    label?: string | null;
    title?: string | null;
    milestones?:
      | {
          year: string;
          title: string;
          description?: string | null;
          align_right?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  experts_section?: {
    label?: string | null;
    title?: string | null;
    experts?:
      | {
          name: string;
          role: string;
          /**
           * Recommended: square image, e.g. 220x220px
           */
          image?: (number | null) | Media;
          description: string;
          social_links?: {
            /**
             * Leave empty to hide the icon
             */
            x?: string | null;
            /**
             * Leave empty to hide the icon
             */
            facebook?: string | null;
            /**
             * Leave empty to hide the icon
             */
            linkedin?: string | null;
            /**
             * Leave empty to hide the icon
             */
            telegram?: string | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_content".
 */
export interface EventsContent {
  id: number;
  hero_section?: {
    /**
     * Select an event to display in the hero section
     */
    featured_event?: (number | null) | Event;
    label?: string | null;
    /**
     * Upload a custom image. If empty, will use the featured event image.
     */
    image?: (number | null) | Media;
    buttons?:
      | {
          text: string;
          url?: string | null;
          style: 'primary' | 'secondary';
          show_arrow?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  key_dates_section?: {
    label?: string | null;
    title?: string | null;
  };
  thematic_areas_section?: {
    label?: string | null;
    title?: string | null;
  };
  speakers_section?: {
    label?: string | null;
    title?: string | null;
    speakers?:
      | {
          name: string;
          role: string;
          image?: (number | null) | Media;
          description: string;
          social_links?: {
            x?: string | null;
            linkedin?: string | null;
            facebook?: string | null;
            telegram?: string | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  sessions_section?: {
    label?: string | null;
    title?: string | null;
  };
  registration_section: {
    label?: string | null;
    title?: string | null;
    left_box: {
      icon?: ('document_green.png' | 'document_yellow.png') | null;
      title: string;
      description: string;
      button_text: string;
      button_url?: string | null;
    };
    right_box: {
      icon?: ('document_green.png' | 'document_yellow.png') | null;
      title: string;
      description: string;
      button_text: string;
      button_url?: string | null;
    };
  };
  past_events_section?: {
    label?: string | null;
    title?: string | null;
    view_all_text?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_content".
 */
export interface PublicationsContent {
  id: number;
  hero_section?: {
    label?: string | null;
    title?: string | null;
    description?: string | null;
  };
  filters_section?: {
    all_label?: string | null;
    file_type_label?: string | null;
    publication_year_label?: string | null;
  };
  pagination_section?: {
    prev_label?: string | null;
    next_label?: string | null;
  };
  download_button_label?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_content".
 */
export interface MediaContent {
  id: number;
  photos_section?: {
    label?: string | null;
    title?: string | null;
    /**
     * Select up to 9 albums to display on the media page.
     */
    albums?: (number | AlbumMedia)[] | null;
    view_all_text?: string | null;
    view_all_link?: string | null;
  };
  press_section?: {
    label?: string | null;
    title?: string | null;
    press_releases?: (number | PressMedia)[] | null;
    view_all_text?: string | null;
    view_all_link?: string | null;
  };
  media_kit_section?: {
    label?: string | null;
    title?: string | null;
    description?: string | null;
    view_all_text?: string | null;
    view_all_link?: string | null;
    resources?:
      | {
          image: number | Media;
          title: string;
          type: string;
          size: string;
          file?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_settings".
 */
export interface SiteSetting {
  id: number;
  header?: {
    about_label?: string | null;
    events_label?: string | null;
    events_upcoming_label?: string | null;
    events_past_label?: string | null;
    publications_label?: string | null;
    media_label?: string | null;
  };
  footer?: {
    description?: string | null;
    home_label?: string | null;
    about_label?: string | null;
    events_label?: string | null;
    upcoming_label?: string | null;
    past_label?: string | null;
    publications_label?: string | null;
    media_label?: string | null;
    press_label?: string | null;
    media_kit_label?: string | null;
    copyright_text?: string | null;
    privacy_label?: string | null;
    terms_label?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_content_select".
 */
export interface HomepageContentSelect<T extends boolean = true> {
  hero_section?:
    | T
    | {
        featured_event?: T;
        background_image?: T;
        title?: T;
        subtitle?: T;
        register_cta?: T;
        register_cta_url?: T;
        explore_cta?: T;
        explore_cta_url?: T;
      };
  about_section?:
    | T
    | {
        label?: T;
        title?: T;
        description?: T;
        boxes?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  upcoming_forum_section?:
    | T
    | {
        featured_event?: T;
        label?: T;
        register_cta?: T;
        register_cta_url?: T;
        view_program_cta?: T;
        view_program_cta_url?: T;
      };
  publications_section?:
    | T
    | {
        label?: T;
        title?: T;
        view_all_text?: T;
        download_cta?: T;
      };
  contact_section?:
    | T
    | {
        label?: T;
        title?: T;
        description?: T;
        contact_items?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        form_name_placeholder?: T;
        form_name_label?: T;
        form_email_placeholder?: T;
        form_email_label?: T;
        form_subject_placeholder?: T;
        form_subject_label?: T;
        form_message_placeholder?: T;
        form_message_label?: T;
        form_privacy_text?: T;
        form_submit_cta?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_content_select".
 */
export interface AboutContentSelect<T extends boolean = true> {
  hero_section?:
    | T
    | {
        label?: T;
        title?: T;
        description?: T;
        image?: T;
      };
  mission_section?:
    | T
    | {
        label?: T;
        title?: T;
        description?: T;
        read_more_text?: T;
        read_more_url?: T;
        objectives?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  milestones_section?:
    | T
    | {
        label?: T;
        title?: T;
        milestones?:
          | T
          | {
              year?: T;
              title?: T;
              description?: T;
              align_right?: T;
              id?: T;
            };
      };
  experts_section?:
    | T
    | {
        label?: T;
        title?: T;
        experts?:
          | T
          | {
              name?: T;
              role?: T;
              image?: T;
              description?: T;
              social_links?:
                | T
                | {
                    x?: T;
                    facebook?: T;
                    linkedin?: T;
                    telegram?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_content_select".
 */
export interface EventsContentSelect<T extends boolean = true> {
  hero_section?:
    | T
    | {
        featured_event?: T;
        label?: T;
        image?: T;
        buttons?:
          | T
          | {
              text?: T;
              url?: T;
              style?: T;
              show_arrow?: T;
              id?: T;
            };
      };
  key_dates_section?:
    | T
    | {
        label?: T;
        title?: T;
      };
  thematic_areas_section?:
    | T
    | {
        label?: T;
        title?: T;
      };
  speakers_section?:
    | T
    | {
        label?: T;
        title?: T;
        speakers?:
          | T
          | {
              name?: T;
              role?: T;
              image?: T;
              description?: T;
              social_links?:
                | T
                | {
                    x?: T;
                    linkedin?: T;
                    facebook?: T;
                    telegram?: T;
                  };
              id?: T;
            };
      };
  sessions_section?:
    | T
    | {
        label?: T;
        title?: T;
      };
  registration_section?:
    | T
    | {
        label?: T;
        title?: T;
        left_box?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              button_text?: T;
              button_url?: T;
            };
        right_box?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              button_text?: T;
              button_url?: T;
            };
      };
  past_events_section?:
    | T
    | {
        label?: T;
        title?: T;
        view_all_text?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_content_select".
 */
export interface PublicationsContentSelect<T extends boolean = true> {
  hero_section?:
    | T
    | {
        label?: T;
        title?: T;
        description?: T;
      };
  filters_section?:
    | T
    | {
        all_label?: T;
        file_type_label?: T;
        publication_year_label?: T;
      };
  pagination_section?:
    | T
    | {
        prev_label?: T;
        next_label?: T;
      };
  download_button_label?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_content_select".
 */
export interface MediaContentSelect<T extends boolean = true> {
  photos_section?:
    | T
    | {
        label?: T;
        title?: T;
        albums?: T;
        view_all_text?: T;
        view_all_link?: T;
      };
  press_section?:
    | T
    | {
        label?: T;
        title?: T;
        press_releases?: T;
        view_all_text?: T;
        view_all_link?: T;
      };
  media_kit_section?:
    | T
    | {
        label?: T;
        title?: T;
        description?: T;
        view_all_text?: T;
        view_all_link?: T;
        resources?:
          | T
          | {
              image?: T;
              title?: T;
              type?: T;
              size?: T;
              file?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  header?:
    | T
    | {
        about_label?: T;
        events_label?: T;
        events_upcoming_label?: T;
        events_past_label?: T;
        publications_label?: T;
        media_label?: T;
      };
  footer?:
    | T
    | {
        description?: T;
        home_label?: T;
        about_label?: T;
        events_label?: T;
        upcoming_label?: T;
        past_label?: T;
        publications_label?: T;
        media_label?: T;
        press_label?: T;
        media_kit_label?: T;
        copyright_text?: T;
        privacy_label?: T;
        terms_label?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}