import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "ASEAN Biodiversity Science Forum",
  description: "Generated by create next app",
  icons: {
    icon: "/bsf_logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
